import { NextResponse } from "next/server";
import { createClient } from "../../../../lib/supabase/server";
import { createAdminClient } from "../../../../lib/supabase/admin";

export const runtime = "nodejs";

type PublishBody = {
  starFileId?: string;
  previewPath?: string | null;
};

type StarMusicFile = {
  id: string;
  user_id: string;
  title: string;
  description: string | null;
  category: string;
  storage_path: string;
  bpm: number | null;
  musical_key: string | null;
  price_cents: number;
  license_type: string;
  verification_status: string;
  publish_status: string;
  marketplace_item_id: string | null;
};

export async function POST(request: Request) {
  try {
    const body = await request.json() as PublishBody;
    if (!body.starFileId) return NextResponse.json({ error: "Choose a vault file to publish." }, { status: 400 });

    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: "Sign in before publishing." }, { status: 401 });

    const { data, error } = await supabase
      .from("star_music_files")
      .select("id,user_id,title,description,category,storage_path,bpm,musical_key,price_cents,license_type,verification_status,publish_status,marketplace_item_id")
      .eq("id", body.starFileId)
      .eq("user_id", user.id)
      .single();
    if (error || !data) return NextResponse.json({ error: "Vault file not found." }, { status: 404 });
    const file = data as StarMusicFile;
    if (file.verification_status === "failed") return NextResponse.json({ error: "A failed File DNA check cannot be published." }, { status: 400 });
    if (file.marketplace_item_id || file.publish_status === "published") {
      return NextResponse.json({ itemId: file.marketplace_item_id, alreadyPublished: true });
    }
    if (!file.storage_path.startsWith(`${user.id}/`)) return NextResponse.json({ error: "Invalid private master path." }, { status: 400 });

    const paid = file.price_cents > 0;
    const previewPath = body.previewPath?.trim() || null;
    if (paid && (!previewPath || !previewPath.startsWith(`${user.id}/marketplace-previews/`))) {
      return NextResponse.json({ error: "Paid sounds require the protected preview generated by Forge." }, { status: 400 });
    }

    const admin = createAdminClient();
    await admin.from("marketplace_sellers").upsert({
      user_id: user.id,
      display_name: user.email?.split("@")[0] || "Crucible Artist",
    }, { onConflict: "user_id" }).throwOnError();

    const marketplaceCategory = ["beat", "loop", "sample", "one-shot", "preset", "other"].includes(file.category)
      ? file.category
      : "other";
    const { data: listing, error: listingError } = await admin.from("sound_library_items").insert({
      user_id: user.id,
      title: file.title,
      description: file.description,
      category: marketplaceCategory,
      file_url: `star-music:${file.storage_path}`,
      preview_url: previewPath ? `star-music:${previewPath}` : null,
      price_cents: file.price_cents,
      free_download: !paid,
      bpm: file.bpm,
      musical_key: file.musical_key,
      license_type: file.license_type,
      is_published: true,
      watermark_label: "CRUCIBLE PREVIEW · PROTECTED MASTER",
    }).select("id").single();
    if (listingError || !listing) throw listingError || new Error("The marketplace listing was not created.");

    const { error: updateError } = await admin.from("star_music_files").update({
      marketplace_item_id: listing.id,
      publish_status: "published",
      updated_at: new Date().toISOString(),
    }).eq("id", file.id).eq("user_id", user.id);
    if (updateError) {
      await admin.from("sound_library_items").delete().eq("id", listing.id);
      throw updateError;
    }

    return NextResponse.json({ itemId: listing.id, published: true });
  } catch (error) {
    return NextResponse.json({ error: error instanceof Error ? error.message : "Marketplace publishing failed." }, { status: 500 });
  }
}
