import { NextResponse } from "next/server";
import { createClient } from "../../../../lib/supabase/server";
import { adminRequest } from "../../../../lib/billing/admin";
import { getBillingConfig,getStripeClient } from "../../../../lib/billing/stripe";

export const runtime="nodejs";
export async function POST(request:Request){
 const sb=await createClient(); const {data:{user}}=await sb.auth.getUser(); if(!user)return NextResponse.json({error:"Sign in to buy this item."},{status:401});
 const {itemId}=await request.json() as {itemId?:string}; if(!itemId)return NextResponse.json({error:"Missing item."},{status:400});
 const items=await adminRequest<Array<{id:string;title:string;user_id:string|null;price_cents:number;free_download:boolean;is_published:boolean}>>(`sound_library_items?id=eq.${encodeURIComponent(itemId)}&select=id,title,user_id,price_cents,free_download,is_published&limit=1`); const item=items[0]; if(!item?.is_published)return NextResponse.json({error:"Item unavailable."},{status:404}); if(item.free_download||item.price_cents<=0)return NextResponse.json({url:`/api/marketplace/download?id=${encodeURIComponent(item.id)}`}); if(!item.user_id)return NextResponse.json({error:"Seller unavailable."},{status:400}); if(item.user_id===user.id)return NextResponse.json({error:"You already own the master as its seller."},{status:400});
 const sellers=await adminRequest<Array<{stripe_account_id:string|null}>>(`marketplace_sellers?user_id=eq.${item.user_id}&select=stripe_account_id&limit=1`); const destination=sellers[0]?.stripe_account_id; if(!destination)return NextResponse.json({error:"Seller has not completed payout setup yet."},{status:409}); const {secretKey}=getBillingConfig(); if(!secretKey)return NextResponse.json({error:"Checkout unavailable."},{status:503});
 const purchaseRows=await adminRequest<Array<{id:string}>>("marketplace_purchases",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({buyer_id:user.id,item_id:item.id,seller_id:item.user_id,amount_cents:item.price_cents,payment_status:"pending"})}); const purchase=purchaseRows[0]; if(!purchase)return NextResponse.json({error:"Could not reserve purchase."},{status:500});
 const stripe=getStripeClient(secretKey); const origin=new URL(request.url).origin; const fee=Math.min(item.price_cents,Math.round(item.price_cents*0.10)); const session=await stripe.checkout.sessions.create({mode:"payment",customer_email:user.email??undefined,line_items:[{quantity:1,price_data:{currency:"usd",unit_amount:item.price_cents,product_data:{name:item.title,description:"Crucible marketplace digital audio license"}}}],payment_intent_data:{application_fee_amount:fee,transfer_data:{destination}},success_url:`${origin}/api/marketplace/confirm?session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${origin}/sound-library?purchase=cancelled`,metadata:{marketplace_purchase_id:purchase.id,item_id:item.id,buyer_id:user.id,seller_id:item.user_id}}); await adminRequest(`marketplace_purchases?id=eq.${purchase.id}`,{method:"PATCH",body:JSON.stringify({stripe_checkout_session_id:session.id})}); return NextResponse.json({url:session.url});
}
