"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "../../lib/supabase/client";
import { BadgeDollarSign, Download, Music2, Play, Plus, ShieldCheck, Store } from "lucide-react";

type Item={id:string;user_id:string|null;title:string;description:string|null;category:string;artwork_url:string|null;free_download:boolean;price_cents:number;preview_url:string|null;watermark_label:string;bpm:number|null;musical_key:string|null;license_type:string;created_at:string};
export default function SoundLibraryPage(){
 const [items,setItems]=useState<Item[]>([]),[query,setQuery]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[selling,setSelling]=useState(false);
 const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[category,setCategory]=useState("beat"),[masterUrl,setMasterUrl]=useState(""),[previewUrl,setPreviewUrl]=useState(""),[price,setPrice]=useState("0"),[bpm,setBpm]=useState("");
 const load=async()=>{const sb=createClient();const {data,error}=await sb.from("sound_library_items").select("id,user_id,title,description,category,artwork_url,free_download,price_cents,preview_url,watermark_label,bpm,musical_key,license_type,created_at").eq("is_published",true).order("created_at",{ascending:false}).limit(100);if(error)setMsg(error.message);else setItems((data??[]) as Item[])}; useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>items.filter(i=>`${i.title} ${i.description??""} ${i.category}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 const list=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMsg("");const sb=createClient();const {data:{user}}=await sb.auth.getUser();if(!user){setMsg("Sign in to sell or share sounds.");setBusy(false);return;}const cents=Math.max(0,Math.round(Number(price||0)*100));if(cents>0&&!previewUrl.trim()){setMsg("Paid items require a separate watermarked preview URL. The master file is never exposed for preview.");setBusy(false);return;}await sb.from("marketplace_sellers").upsert({user_id:user.id,display_name:user.email?.split("@")[0]||"Crucible Artist"},{onConflict:"user_id"});const {error}=await sb.from("sound_library_items").insert({user_id:user.id,title:title.trim(),description:description.trim()||null,category,file_url:masterUrl.trim(),preview_url:previewUrl.trim()||null,price_cents:cents,free_download:cents===0,bpm:bpm?Number(bpm):null,is_published:true,watermark_label:"CRUCIBLE PREVIEW"});if(error)setMsg(error.message);else{setTitle("");setDescription("");setMasterUrl("");setPreviewUrl("");setPrice("0");setBpm("");setSelling(false);await load();}setBusy(false);};
 const buy=async(id:string)=>{setMsg("");const r=await fetch("/api/marketplace/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId:id})});const data=await r.json();if(!r.ok){setMsg(data.error||"Checkout failed.");return;}if(data.url)location.href=data.url;};
 const onboard=async()=>{const r=await fetch("/api/marketplace/seller-onboard",{method:"POST"});const data=await r.json();if(!r.ok){setMsg(data.error||"Seller setup failed.");return;}if(data.url)location.href=data.url;};
 return <main className="min-h-screen bg-[#050403] pb-28 text-white"><div className="mx-auto max-w-6xl px-4 py-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-orange-300">Crucible market</p><h1 className="mt-2 text-3xl font-black">Sounds</h1><p className="mt-2 max-w-2xl text-sm text-white/45">Free downloads plus artist-sold beats, loops, drums and samples. Paid masters stay protected behind checkout.</p></div><div className="flex gap-2"><button onClick={()=>void onboard()} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-black"><Store size={14} className="mr-1 inline"/>Seller payout setup</button><button onClick={()=>setSelling(v=>!v)} className="rounded-xl bg-orange-500 px-3 py-2 text-xs font-black text-black"><Plus size={14} className="mr-1 inline"/>List sound</button></div></header>
 {selling?<form onSubmit={list} className="mt-5 grid gap-3 rounded-3xl border border-orange-300/15 bg-[#0d0a08] p-4 sm:grid-cols-2"><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm"/><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm"><option>beat</option><option>loop</option><option>drum</option><option>sample</option><option>preset</option></select><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description" className="rounded-xl border border-white/10 bg-black/30 p-3 text-sm sm:col-span-2"/><input required value={masterUrl} onChange={e=>setMasterUrl(e.target.value)} placeholder="Master/download file URL (kept protected)" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm sm:col-span-2"/><input value={previewUrl} onChange={e=>setPreviewUrl(e.target.value)} placeholder="Watermarked preview URL — required for paid items" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm sm:col-span-2"/><input inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Price, e.g. 19.99 (0 = free)" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm"/><input inputMode="numeric" value={bpm} onChange={e=>setBpm(e.target.value)} placeholder="BPM optional" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm"/><button disabled={busy} className="w-fit rounded-xl bg-orange-500 px-4 py-2 text-sm font-black text-black">{busy?"Publishing…":"Publish listing"}</button></form>:null}
 <div className="mt-5"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search beats, loops, drums, samples…" className="w-full rounded-2xl border border-white/10 bg-[#0d0a08] px-4 py-3 text-sm outline-none"/></div>{msg?<p className="mt-3 rounded-xl border border-orange-300/20 bg-orange-500/10 p-3 text-xs text-orange-100">{msg}</p>:null}
 <section className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(i=>{const paid=i.price_cents>0;const audioSrc=paid?i.preview_url:`/api/marketplace/download?id=${encodeURIComponent(i.id)}&preview=1`;return <article key={i.id} className="overflow-hidden rounded-3xl border border-white/10 bg-[#0d0a08] p-4"><div className="flex items-center justify-between"><span className="rounded-full bg-white/5 px-2 py-1 text-[9px] font-black uppercase tracking-wider text-white/45">{i.category}</span><span className="text-sm font-black text-orange-300">{paid?`$${(i.price_cents/100).toFixed(2)}`:"FREE"}</span></div><h2 className="mt-4 text-lg font-black">{i.title}</h2><p className="mt-1 min-h-10 text-xs leading-5 text-white/40">{i.description||"Crucible artist sound."}</p><div className="mt-3 flex gap-2 text-[10px] text-white/35">{i.bpm?<span>{i.bpm} BPM</span>:null}<span>{i.license_type}</span></div>{audioSrc?<div className="mt-4"><audio controls preload="none" className="w-full" src={audioSrc}/>{paid?<div className="mt-2 flex items-center gap-1 text-[9px] font-black uppercase tracking-wider text-amber-300"><ShieldCheck size={13}/>{i.watermark_label}</div>:null}</div>:paid?<p className="mt-4 text-xs text-amber-200">Seller must attach a protected preview before this item can be auditioned.</p>:null}<div className="mt-4">{paid?<button onClick={()=>void buy(i.id)} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2 text-xs font-black text-black"><BadgeDollarSign size={15}/>Buy license</button>:<a href={`/api/marketplace/download?id=${encodeURIComponent(i.id)}`} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2 text-xs font-black text-black"><Download size={15}/>Download</a>}</div></article>})}</section>{filtered.length===0?<div className="mt-6 rounded-2xl border border-dashed border-white/10 p-10 text-center text-white/30"><Music2 className="mx-auto mb-2"/>No sounds match yet.</div>:null}</div></main>;
}
