"use client";

import { FormEvent, useEffect, useState } from "react";
import { createClient } from "../../lib/supabase/client";
import { LibraryBig, Plus, Trash2 } from "lucide-react";

type Item={id:string;title:string;kind:string;audio_url:string|null;created_at:string};
export default function LocalLibraryPage(){
 const [items,setItems]=useState<Item[]>([]),[title,setTitle]=useState(""),[url,setUrl]=useState(""),[kind,setKind]=useState("track"),[msg,setMsg]=useState("");
 const load=async()=>{const sb=createClient();const {data:{user}}=await sb.auth.getUser();if(!user){setMsg("Sign in to open your private library.");return;}const {data,error}=await sb.from("private_music_library").select("id,title,kind,audio_url,created_at").order("created_at",{ascending:false});if(error)setMsg(error.message);else setItems((data??[]) as Item[]);}; useEffect(()=>{void load();},[]);
 const add=async(e:FormEvent)=>{e.preventDefault();const sb=createClient();const {data:{user}}=await sb.auth.getUser();if(!user){setMsg("Sign in first.");return;}const {error}=await sb.from("private_music_library").insert({user_id:user.id,title:title.trim(),kind,audio_url:url.trim()||null});if(error)setMsg(error.message);else{setTitle("");setUrl("");setMsg("");await load();}};
 const remove=async(id:string)=>{const sb=createClient();await sb.from("private_music_library").delete().eq("id",id);await load();};
 return <main className="min-h-screen bg-[#050403] pb-28 text-white"><div className="mx-auto max-w-4xl px-4 py-6"><p className="text-[10px] font-black uppercase tracking-[.25em] text-orange-300">Private vault</p><h1 className="mt-2 text-3xl font-black">My Library</h1><p className="mt-2 text-sm text-white/45">Your private tracks, works in progress and saved mixes. Other artists cannot see this library.</p>
 <form onSubmit={add} className="mt-6 grid gap-3 rounded-2xl border border-white/10 bg-[#0d0a08] p-4 sm:grid-cols-[1fr_150px]"><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Track or project title" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm"/><select value={kind} onChange={e=>setKind(e.target.value)} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm"><option value="track">Track</option><option value="mix">Mix</option><option value="project">Project</option><option value="demo">Demo</option></select><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Optional private audio URL" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm sm:col-span-2"/><button className="inline-flex w-fit items-center gap-2 rounded-xl bg-orange-500 px-4 py-2 text-sm font-black text-black"><Plus size={16}/>Add to Library</button></form>{msg?<p className="mt-3 text-xs text-orange-200">{msg}</p>:null}
 <section className="mt-6 grid gap-3 sm:grid-cols-2">{items.length===0?<div className="sm:col-span-2 rounded-2xl border border-dashed border-white/10 p-8 text-center text-white/35"><LibraryBig className="mx-auto mb-2"/>Your private library is empty.</div>:items.map(x=><article key={x.id} className="rounded-2xl border border-white/10 bg-[#0d0a08] p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-[9px] font-black uppercase tracking-wider text-orange-300">{x.kind}</span><h2 className="mt-1 font-black">{x.title}</h2></div><button onClick={()=>void remove(x.id)} aria-label="Delete" className="rounded-lg border border-white/10 p-2 text-white/40"><Trash2 size={15}/></button></div>{x.audio_url?<audio className="mt-4 w-full" controls preload="none" src={x.audio_url}/>:null}</article>)}</section></div></main>;
}
